# Generated by Django 2.1.5 on 2019-02-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('passout_year', models.IntegerField()),
                ('phonenumber', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
    ]
