# Generated by Django 2.1.5 on 2019-02-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sportsbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChestNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DutyLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=100)),
                ('passout_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='dutyleave',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='chestno',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
        migrations.AddField(
            model_name='chestno',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsbackend.Year'),
        ),
    ]
