# Generated by Django 2.1.5 on 2019-02-14 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbackend', '0002_auto_20190212_1717'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyleave',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dutyleave',
            name='year',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='sportsbackend.Year'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dutyleave',
            name='hour',
            field=models.CharField(max_length=100),
        ),
    ]
