# Generated by Django 2.1.5 on 2019-02-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
