# Generated by Django 2.1.5 on 2019-02-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbackend', '0002_year_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participate',
            name='position',
            field=models.IntegerField(choices=[(0, 'Registered'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Participated'), (6, 'University'), (7, 'District'), (8, 'State'), (9, 'National'), (10, 'International')], default=0),
        ),
    ]
