# Generated by Django 2.1.5 on 2019-04-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbackend', '0003_auto_20190411_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participate',
            name='position',
            field=models.IntegerField(blank=True, choices=[(0, 'Registered'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Participated'), (6, 'University'), (7, 'District'), (8, 'State'), (9, 'National'), (10, 'International')], default=0, null=True),
        ),
    ]
